version: '3.7'

x-base-dev: &base-dev
  restart: on-failure


services:

  python:
    <<: *base-dev
    build:
      context: .
      target: airflow
    volumes:
      - ./src:/src
      - .:/project
      - airflow_home:/airflow

  airflow:
    <<: *base-dev
    build:
      context: .
      target: airflow
    volumes:
      - ./src:/src
      - .:/project
      - airflow_home:/airflow
    entrypoint: ["/project/bin/entrypoint.py"]



volumes:
  airflow_home: