version: '3.7'

x-base-dev: &base-dev
  restart: on-failure
  volumes:
    - ./src:/src
    - .:/project
    - airflow_home:/airflow


services:

  python:
    <<: *base-dev
    build:
      context: .
      target: airflow
    volumes:
      - ./src:/src
      - .:/project
      - ./data/airflow:/airflow

  airflow_scheduler:
    <<: *base-dev
    build:
      context: .
      target: airflow
    entrypoint: ["python"]
    command: ['/project/bin/entrypoint.py', 'scheduler']


  airflow_webserver:
    <<: *base-dev
    build:
      context: .
      target: airflow
    entrypoint: ["python"]
    command: ['/project/bin/entrypoint.py', 'webserver']
    ports:
      - "8080:8080"
    depends_on:
      - "airflow_scheduler"

  airflow_worker:
    <<: *base-dev
    build:
      context: .
      target: airflow
    entrypoint: ["python"]
    command: ['/project/bin/entrypoint.py', 'worker']
    ports:
      - "8080:8080"
    depends_on:
      - "airflow_scheduler"



volumes:
  airflow_home: